/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/DAT-01'
export * from './tasks/DAT-02'
export * from './tasks/DAT-03'
export * from './tasks/DAT-04'
export * from './tasks/DAT-05'
export * from './tasks/DAT-06'
export * from './tasks/DAT-07'
export * from './tasks/DAT-08'
export * from './tasks/DAT-09'
export * from './tasks/DAT-10'
export * from './tasks/DAT-11'
export * from './tasks/DAT-12'
export * from './tasks/DAT-13'
export * from './tasks/DAT-14'
export * from './tasks/DAT-15'
export * from './tasks/DAT-16'
export * from './tasks/DAT-17'
export * from './tasks/DAT-18'
export * from './tasks/DAT-19'
export * from './tasks/DAT-20'
export * from './tasks/DAT-21'
export * from './tasks/DAT-22'
export * from './tasks/DAT-23'
export * from './tasks/DAT-24'
