/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/ARR-01'
export * from './tasks/ARR-02'
export * from './tasks/ARR-03'
export * from './tasks/ARR-04'
export * from './tasks/ARR-05'
export * from './tasks/ARR-06'
export * from './tasks/ARR-07'
export * from './tasks/ARR-08'
export * from './tasks/ARR-09'
export * from './tasks/ARR-10'
export * from './tasks/ARR-11'
export * from './tasks/ARR-12'
export * from './tasks/ARR-13'
export * from './tasks/ARR-14'
export * from './tasks/ARR-15'
export * from './tasks/ARR-16'
export * from './tasks/ARR-17'
export * from './tasks/ARR-18'
export * from './tasks/ARR-19'
export * from './tasks/ARR-20'
export * from './tasks/ARR-21'
export * from './tasks/ARR-22'
export * from './tasks/ARR-23'
export * from './tasks/ARR-24'
export * from './tasks/ARR-25'
export * from './tasks/ARR-26'
export * from './tasks/ARR-27'
export * from './tasks/ARR-28'
export * from './tasks/ARR-29'
export * from './tasks/ARR-30'
export * from './tasks/ARR-31'
export * from './tasks/ARR-32'
