/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/BAS-01'
export * from './tasks/BAS-02'
export * from './tasks/BAS-03'
export * from './tasks/BAS-04'
export * from './tasks/BAS-05'
export * from './tasks/BAS-06'
export * from './tasks/BAS-07'
export * from './tasks/BAS-08'
export * from './tasks/BAS-09'
export * from './tasks/BAS-10'
export * from './tasks/BAS-11'
export * from './tasks/BAS-12'
export * from './tasks/BAS-13'
export * from './tasks/BAS-14'
export * from './tasks/BAS-15'
export * from './tasks/BAS-16'
export * from './tasks/BAS-17'
export * from './tasks/BAS-18'
export * from './tasks/BAS-19'
export * from './tasks/BAS-20'
export * from './tasks/BAS-21'
export * from './tasks/BAS-22'
export * from './tasks/BAS-23'
export * from './tasks/BAS-24'
