/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/TSB-01'
export * from './tasks/TSB-02'
export * from './tasks/TSB-03'
export * from './tasks/TSB-04'
export * from './tasks/TSB-05'
export * from './tasks/TSB-06'
export * from './tasks/TSB-07'
export * from './tasks/TSB-08'
export * from './tasks/TSB-09'
export * from './tasks/TSB-10'
export * from './tasks/TSB-11'
export * from './tasks/TSB-12'
export * from './tasks/TSB-13'
export * from './tasks/TSB-14'
export * from './tasks/TSB-15'
export * from './tasks/TSB-16'
export * from './tasks/TSB-17'
export * from './tasks/TSB-18'
export * from './tasks/TSB-19'
export * from './tasks/TSB-20'
export * from './tasks/TSB-21'
export * from './tasks/TSB-22'
export * from './tasks/TSB-23'
export * from './tasks/TSB-24'
export * from './tasks/TSB-25'
export * from './tasks/TSB-26'
export * from './tasks/TSB-27'
export * from './tasks/TSB-28'
export * from './tasks/TSB-29'
export * from './tasks/TSB-30'
