/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/QZ-01'
export * from './tasks/QZ-02'
export * from './tasks/QZ-03'
export * from './tasks/QZ-04'
export * from './tasks/QZ-05'
export * from './tasks/QZ-06'
export * from './tasks/QZ-07'
export * from './tasks/QZ-08'
export * from './tasks/QZ-09'
export * from './tasks/QZ-10'
export * from './tasks/QZ-11'
export * from './tasks/QZ-12'
export * from './tasks/QZ-13'
export * from './tasks/QZ-14'
export * from './tasks/QZ-15'
export * from './tasks/QZ-16'
export * from './tasks/QZ-17'
export * from './tasks/QZ-18'
export * from './tasks/QZ-19'
export * from './tasks/QZ-20'
export * from './tasks/QZ-21'
export * from './tasks/QZ-22'
export * from './tasks/QZ-23'
export * from './tasks/QZ-24'
export * from './tasks/QZ-25'
export * from './tasks/QZ-26'
export * from './tasks/QZ-27'
export * from './tasks/QZ-28'
export * from './tasks/QZ-29'
export * from './tasks/QZ-30'
export * from './tasks/QZ-31'
export * from './tasks/QZ-32'
export * from './tasks/QZ-33'
export * from './tasks/QZ-34'
export * from './tasks/QZ-35'
export * from './tasks/QZ-36'
export * from './tasks/QZ-37'
export * from './tasks/QZ-38'
export * from './tasks/QZ-39'
export * from './tasks/QZ-40'
