/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/TS-01'
export * from './tasks/TS-02'
export * from './tasks/TS-03'
export * from './tasks/TS-04'
export * from './tasks/TS-05'
export * from './tasks/TS-06'
export * from './tasks/TS-07'
export * from './tasks/TS-08'
export * from './tasks/TS-09'
export * from './tasks/TS-10'
export * from './tasks/TS-11'
export * from './tasks/TS-12'
export * from './tasks/TS-13'
export * from './tasks/TS-14'
export * from './tasks/TS-15'
export * from './tasks/TS-16'
export * from './tasks/TS-17'
export * from './tasks/TS-18'
export * from './tasks/TS-19'
export * from './tasks/TS-20'
export * from './tasks/TS-21'
export * from './tasks/TS-22'
export * from './tasks/TS-23'
export * from './tasks/TS-24'
export * from './tasks/TS-25'
export * from './tasks/TS-26'
