/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/ALG-01'
export * from './tasks/ALG-02'
export * from './tasks/ALG-03'
export * from './tasks/ALG-04'
export * from './tasks/ALG-05'
export * from './tasks/ALG-06'
export * from './tasks/ALG-07'
export * from './tasks/ALG-08'
export * from './tasks/ALG-09'
export * from './tasks/ALG-10'
export * from './tasks/ALG-11'
export * from './tasks/ALG-12'
export * from './tasks/ALG-13'
export * from './tasks/ALG-14'
export * from './tasks/ALG-15'
export * from './tasks/ALG-16'
export * from './tasks/ALG-17'
export * from './tasks/ALG-18'
export * from './tasks/ALG-19'
export * from './tasks/ALG-20'
export * from './tasks/ALG-21'
export * from './tasks/ALG-22'
export * from './tasks/ALG-23'
export * from './tasks/ALG-24'
export * from './tasks/ALG-25'
export * from './tasks/ALG-26'
