/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/UTL-01'
export * from './tasks/UTL-02'
export * from './tasks/UTL-03'
export * from './tasks/UTL-04'
export * from './tasks/UTL-05'
export * from './tasks/UTL-06'
export * from './tasks/UTL-07'
export * from './tasks/UTL-08'
export * from './tasks/UTL-09'
export * from './tasks/UTL-10'
export * from './tasks/UTL-11'
export * from './tasks/UTL-12'
export * from './tasks/UTL-13'
export * from './tasks/UTL-14'
export * from './tasks/UTL-15'
export * from './tasks/UTL-16'
export * from './tasks/UTL-17'
export * from './tasks/UTL-18'
export * from './tasks/UTL-19'
export * from './tasks/UTL-20'
export * from './tasks/UTL-21'
export * from './tasks/UTL-22'
export * from './tasks/UTL-23'
export * from './tasks/UTL-24'
