/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/FUN-01'
export * from './tasks/FUN-02'
export * from './tasks/FUN-03'
export * from './tasks/FUN-04'
export * from './tasks/FUN-05'
export * from './tasks/FUN-06'
export * from './tasks/FUN-07'
export * from './tasks/FUN-08'
export * from './tasks/FUN-09'
export * from './tasks/FUN-10'
export * from './tasks/FUN-11'
export * from './tasks/FUN-12'
export * from './tasks/FUN-13'
export * from './tasks/FUN-14'
export * from './tasks/FUN-15'
export * from './tasks/FUN-16'
export * from './tasks/FUN-17'
export * from './tasks/FUN-18'
export * from './tasks/FUN-19'
export * from './tasks/FUN-20'
export * from './tasks/FUN-21'
export * from './tasks/FUN-22'
export * from './tasks/FUN-23'
export * from './tasks/FUN-24'
