/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/RH-01'
export * from './tasks/RH-02'
export * from './tasks/RH-03'
export * from './tasks/RH-04'
export * from './tasks/RH-05'
export * from './tasks/RH-06'
export * from './tasks/RH-07'
export * from './tasks/RH-08'
export * from './tasks/RH-09'
export * from './tasks/RH-10'
export * from './tasks/RH-11'
export * from './tasks/RH-12'
export * from './tasks/RH-13'
export * from './tasks/RH-14'
export * from './tasks/RH-15'
export * from './tasks/RH-16'
export * from './tasks/RH-17'
export * from './tasks/RH-18'
export * from './tasks/RH-19'
export * from './tasks/RH-20'
export * from './tasks/RH-21'
export * from './tasks/RH-22'
export * from './tasks/RH-23'
export * from './tasks/RH-24'
export * from './tasks/RH-25'
export * from './tasks/RH-26'
