/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/FMT-01'
export * from './tasks/FMT-02'
export * from './tasks/FMT-03'
export * from './tasks/FMT-04'
export * from './tasks/FMT-05'
export * from './tasks/FMT-06'
export * from './tasks/FMT-07'
export * from './tasks/FMT-08'
export * from './tasks/FMT-09'
export * from './tasks/FMT-10'
export * from './tasks/FMT-11'
export * from './tasks/FMT-12'
export * from './tasks/FMT-13'
export * from './tasks/FMT-14'
export * from './tasks/FMT-15'
export * from './tasks/FMT-16'
export * from './tasks/FMT-17'
export * from './tasks/FMT-18'
export * from './tasks/FMT-19'
export * from './tasks/FMT-20'
export * from './tasks/FMT-21'
export * from './tasks/FMT-22'
