/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/RB-01'
export * from './tasks/RB-02'
export * from './tasks/RB-03'
export * from './tasks/RB-04'
export * from './tasks/RB-05'
export * from './tasks/RB-06'
export * from './tasks/RB-07'
export * from './tasks/RB-08'
export * from './tasks/RB-09'
export * from './tasks/RB-10'
export * from './tasks/RB-11'
export * from './tasks/RB-12'
export * from './tasks/RB-13'
export * from './tasks/RB-14'
export * from './tasks/RB-15'
export * from './tasks/RB-16'
export * from './tasks/RB-17'
export * from './tasks/RB-18'
export * from './tasks/RB-19'
export * from './tasks/RB-20'
export * from './tasks/RB-21'
export * from './tasks/RB-22'
export * from './tasks/RB-23'
export * from './tasks/RB-24'
export * from './tasks/RB-25'
export * from './tasks/RB-26'
