/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/ASY-01'
export * from './tasks/ASY-02'
export * from './tasks/ASY-03'
export * from './tasks/ASY-04'
export * from './tasks/ASY-05'
export * from './tasks/ASY-06'
export * from './tasks/ASY-07'
export * from './tasks/ASY-08'
export * from './tasks/ASY-09'
export * from './tasks/ASY-10'
export * from './tasks/ASY-11'
export * from './tasks/ASY-12'
export * from './tasks/ASY-13'
export * from './tasks/ASY-14'
export * from './tasks/ASY-15'
export * from './tasks/ASY-16'
export * from './tasks/ASY-17'
export * from './tasks/ASY-18'
export * from './tasks/ASY-19'
export * from './tasks/ASY-20'
export * from './tasks/ASY-21'
export * from './tasks/ASY-22'
export * from './tasks/ASY-23'
export * from './tasks/ASY-24'
export * from './tasks/ASY-25'
export * from './tasks/ASY-26'
