/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/STR-01'
export * from './tasks/STR-02'
export * from './tasks/STR-03'
export * from './tasks/STR-04'
export * from './tasks/STR-05'
export * from './tasks/STR-06'
export * from './tasks/STR-07'
export * from './tasks/STR-08'
export * from './tasks/STR-09'
export * from './tasks/STR-10'
export * from './tasks/STR-11'
export * from './tasks/STR-12'
export * from './tasks/STR-13'
export * from './tasks/STR-14'
export * from './tasks/STR-15'
export * from './tasks/STR-16'
export * from './tasks/STR-17'
export * from './tasks/STR-18'
export * from './tasks/STR-19'
export * from './tasks/STR-20'
export * from './tasks/STR-21'
export * from './tasks/STR-22'
export * from './tasks/STR-23'
export * from './tasks/STR-24'
export * from './tasks/STR-25'
export * from './tasks/STR-26'
export * from './tasks/STR-27'
export * from './tasks/STR-28'
