/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/API-01'
export * from './tasks/API-02'
export * from './tasks/API-03'
export * from './tasks/API-04'
export * from './tasks/API-05'
export * from './tasks/API-06'
export * from './tasks/API-07'
export * from './tasks/API-08'
export * from './tasks/API-09'
export * from './tasks/API-10'
export * from './tasks/API-11'
export * from './tasks/API-12'
export * from './tasks/API-13'
export * from './tasks/API-14'
export * from './tasks/API-15'
export * from './tasks/API-16'
export * from './tasks/API-17'
export * from './tasks/API-18'
export * from './tasks/API-19'
export * from './tasks/API-20'
