/**
 * Задачи пака лежат по одной в файле в папке `tasks/`.
 * Этот файл только собирает их вместе — тесты импортируют его.
 */
export * from './tasks/_pack'
export * from './tasks/OBJ-01'
export * from './tasks/OBJ-02'
export * from './tasks/OBJ-03'
export * from './tasks/OBJ-04'
export * from './tasks/OBJ-05'
export * from './tasks/OBJ-06'
export * from './tasks/OBJ-07'
export * from './tasks/OBJ-08'
export * from './tasks/OBJ-09'
export * from './tasks/OBJ-10'
export * from './tasks/OBJ-11'
export * from './tasks/OBJ-12'
export * from './tasks/OBJ-13'
export * from './tasks/OBJ-14'
export * from './tasks/OBJ-15'
export * from './tasks/OBJ-16'
export * from './tasks/OBJ-17'
export * from './tasks/OBJ-18'
export * from './tasks/OBJ-19'
export * from './tasks/OBJ-20'
export * from './tasks/OBJ-21'
export * from './tasks/OBJ-22'
export * from './tasks/OBJ-23'
export * from './tasks/OBJ-24'
export * from './tasks/OBJ-25'
export * from './tasks/OBJ-26'
export * from './tasks/OBJ-27'
export * from './tasks/OBJ-28'
